# Generated by Django 4.0.3 on 2022-03-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
